# This workflow uses ServiceNow custom actions that are certified by ServiceNow.

name: CD GitHub workflow renamed once

on: workflow_dispatch
  #workflow_run: # @
    #workflows: [ "CI GitHub workflow" ]
    #types: [completed]

jobs:
  registerPackage:
    name: 'Register Package'
    runs-on: ubuntu-latest
    steps:
    # - name: ServiceNow DevOps Register Package
    # # You may pin to the exact commit or the version.           
    #   uses: ServiceNow/servicenow-devops-register-package@v3.1.0
    #   with:
    #       # Devops Integration Token
    #       devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
    #       # ServiceNow Instance URL
    #       instance-url: ${{ secrets.SN_INSTANCE_URL }}
    #       # Orchestration Tool Id of the tool created in ServiceNow
    #       tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
    #       # Github Context
    #       context-github: ${{ toJSON(github) }}
    #       # List of Artifacts in JSON format
    #       artifacts: '[{"name": "app-devops-ci.jar","version": "1.0","semanticVersion": "1.0.0","repositoryName": "${{ github.repository }}" }]'
    #       # Name of the Package that contains list of artifacts
    #       package-name: 'app-devops-change-velocity.war'
    #       # Display Name of Job
    #       job-name: 'Register Package'
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean compile

  change:
    # jobs that must complete successfully before this job will run
    needs: registerPackage
    # type of machine to run the job on
    runs-on: ubuntu-latest
    name: 'ServiceNow DevOps Change'
    steps:
      - name: ServiceNow Change
        uses: ServiceNow/servicenow-devops-change@dev
        with:
          # Devops Integration Token
          devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
          # devops-integration-user-name: '${{ secrets.SN_DEVOPS_USER }}'
          # devops-integration-user-password: '${{ secrets.SN_DEVOPS_PASSWORD }}'
          # ServiceNow Instance URL
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          # Orchestration Tool Id
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          # GitHub Context
          context-github: ${{ toJSON(github) }}
          # Display Name of the Job
          job-name: 'ServiceNow DevOps Change'
          change-request: '{"autoCloseChange":true,"attributes":{"chg_model":{"name": "DevOps"}}}'
          # You can specify the requested_by attribute either with name or sys_id. Example: "requested_by":{"name": "Test User"} or "requested_by": "62826bf03710200044e0bfc8bcbe5df1"
          # You can specify the assignment_group attribute either with name or sys_id. Example: "assignment_group":{"name": "Change Approval Team"} or "assignment_group": "5f721d93c0a8010e015533746de18bf9"
          # start_date: Enter the planned start date
          # end_date: Enter the planned end date

  deploy:
    name: 'Deploy'
    needs: change
    runs-on: ubuntu-latest
    steps:
    - name: Run deployment scripts
      run: echo 'Deployment step in progress...'
