
name: CI on Pull Request

on:
  pull_request:
    branches:
      - main  # Triggers for PRs targeting the 'main' branch
    types: [opened, synchronize, reopened] # Triggers on opening, new commits, or reopening

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
    - name: Run deployment scripts
      run: echo 'Deployment step in progress...'
