name: test_dev_flow
on:
  workflow_call

jobs:
  build:
    name: 'Build'
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
    
    
