name: test_dev_flow
on:
  workflow_call

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo ${{ toJSON(github) }}
      
    
    
