name: test_dev_flow
on:
  workflow_call

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
    - name: Run deployment scripts
      run: echo 'Deployment step in progress...'
      
    
    
